import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navigation";
import { KumaRegistry } from "@kuma-ui/next-plugin/registry"

const inter = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Job Hire Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <KumaRegistry>
          <Navigation />
          {children}
        </KumaRegistry>
          
      </body>
    </html>
  );
}
